import {WIDTH,HEIGHT,clampView,zoomAt,panBy} from '/map-math.js';
const svg=document.getElementById('political-map'),select=document.getElementById('place'),output=document.getElementById('zoom-level');
import {locations as trLocations} from '/atlas-locations.js?v=14';
import {locations as enLocations} from '/atlas-locations-en.js?v=14';
const lang=document.documentElement.lang,locations=lang==='en'?enLocations:trLocations;

let view={x:0,y:0,width:WIDTH,height:HEIGHT};const points=new Map();let drag=null;
function draw(){view=clampView(view);svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.width} ${view.height}`);const zoomFactor=WIDTH/view.width;output.value=zoomFactor.toFixed(1).replace('.0','')+'×';svg.style.setProperty('--map-zoom',zoomFactor.toFixed(2));document.getElementById('zoom-in').disabled=view.width<=WIDTH/5+.01;document.getElementById('zoom-out').disabled=view.width>=WIDTH-.01}
function world(clientX,clientY){const rect=svg.getBoundingClientRect();return {x:view.x+(clientX-rect.left)/rect.width*view.width,y:view.y+(clientY-rect.top)/rect.height*view.height}}
function choose(key,focus=false){const p=locations[key];if(!p)return;select.value=key;document.getElementById('detail-title').textContent=p.title;const flag=document.getElementById('detail-flag');flag.hidden=!p.flag;if(p.flag){flag.src='/'+p.flag+'.svg';flag.alt=p.title+(lang==='en'?' flag':' bayrağı');}document.getElementById('detail-type').textContent=p.type;document.getElementById('detail-text').textContent=p.text;const link=document.getElementById('detail-link');link.href='/?lang='+lang+'#/'+p.slug;link.textContent=lang==='en'?'Open wiki entry ↗':'Wiki maddesini aç ↗';svg.querySelectorAll('[data-location]').forEach(node=>{const active=node.dataset.location===key;node.classList.toggle('selected',active);node.setAttribute('aria-pressed',String(active))});if(focus){const width=p.slug?.includes('kipraya')?WIDTH/4:['anatarya','elonya','veloria','dalmerya','vardena','rovenya','kipraya','avrupa','deniz'].includes(key)?WIDTH/1.8:WIDTH/3;view=clampView({x:p.x-width/2,y:p.y-width*HEIGHT/WIDTH/2,width});draw()}}
function zoom(factor){view=zoomAt(view,factor,view.x+view.width/2,view.y+view.height/2);draw()}
document.getElementById('zoom-in').addEventListener('click',()=>zoom(1.4));document.getElementById('zoom-out').addEventListener('click',()=>zoom(1/1.4));document.getElementById('reset').addEventListener('click',()=>{view={x:0,y:0,width:WIDTH,height:HEIGHT};draw()});select.addEventListener('change',()=>choose(select.value,true));
svg.addEventListener('wheel',e=>{e.preventDefault();const p=world(e.clientX,e.clientY);view=zoomAt(view,Math.exp(-e.deltaY*.0018),p.x,p.y);draw()},{passive:false});
svg.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;svg.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={x:e.clientX,y:e.clientY,moved:points.size>1,key:e.target.closest('[data-location]')?.dataset.location};svg.classList.add('dragging')});
svg.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;const previous=points.get(e.pointerId),before=[...points.values()];points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(points.size===1){const rect=svg.getBoundingClientRect();view=panBy(view,(previous.x-e.clientX)/rect.width*view.width,(previous.y-e.clientY)/rect.height*view.height)}else if(points.size===2){drag.moved=true;const after=[...points.values()];const oldDistance=Math.hypot(before[0].x-before[1].x,before[0].y-before[1].y);const newDistance=Math.hypot(after[0].x-after[1].x,after[0].y-after[1].y);const center=world((before[0].x+before[1].x)/2,(before[0].y+before[1].y)/2);if(oldDistance>0)view=zoomAt(view,newDistance/oldDistance,center.x,center.y)}draw()});
function finish(e){if(!points.has(e.pointerId))return;if(e.type==='pointerup'&&points.size===1&&drag&&!drag.moved&&drag.key)choose(drag.key);points.delete(e.pointerId);if(!points.size){drag=null;svg.classList.remove('dragging')}else if(drag)drag.moved=true}
svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',finish);svg.addEventListener('lostpointercapture',finish);
svg.addEventListener('keydown',e=>{const key=e.target.closest('[data-location]')?.dataset.location;if(key&&['Enter',' '].includes(e.key)){e.preventDefault();choose(key);return}const distance=view.width*.08;let handled=true;if(e.key==='+ '||e.key==='+'||e.key==='=')zoom(1.4);else if(e.key==='-')zoom(1/1.4);else if(e.key==='0'){view={x:0,y:0,width:WIDTH,height:HEIGHT};draw()}else if(e.key==='ArrowLeft')view=panBy(view,-distance,0);else if(e.key==='ArrowRight')view=panBy(view,distance,0);else if(e.key==='ArrowUp')view=panBy(view,0,-distance);else if(e.key==='ArrowDown')view=panBy(view,0,distance);else handled=false;if(handled){e.preventDefault();draw()}});
draw();const requested=new URLSearchParams(location.search).get('yer');if(locations[requested])choose(requested,true);
